---
- secret:
    name: SECRET_DEB_PACKAGING
    data:
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - S8B7Eh87jgE0aasXEuSO3TxvBRtZeFlBdxUySauQ0p/E3UX3ZIyqJrKqZTqQwfg7CJ6/4
          TvD8b9k9Pm9kyUsrGFYwma1cf8rDIIegU9kwmnaA1JT3M/FY2bfN80JhL1/uUpSB6any6
          lWH/aTWEfwpqlzqpeqLXFcRSMugl+H2qfwIm4qWTtR6LbtF6s/TpkhOWOMg6SlJ0IQI5r
          tR/1WDtGNkp+kWzJ9iQR2frwlR0tgjHPbBGqazYLHMzGfDgttNfNxjYLkVh7DcrnB9Hv0
          ZDO68FbQtr7ZQKhObJKnlknIgznnwAu0CUhAkZKmsZpWrH88lQehdUjo525KJSFNZ50FD
          dHmgr6AYykZmJ3zE8n0pdc64H2vnFCe9o5T2BkBQSsuDqDMRDyXaZXFNtqqxnqfIrJQ3F
          sTtUSmIPaxYaVvzdaEWE6ST2Q9d31/U1AN6G6pBrLnmqyFH2l7Ujtj0pHGlW5MU2l1bvh
          TMbQh7So6W1+KEY5PYDlolIJutcw1K3vPOceRK006mx49FOKLKlyMYvBqg6XVwh2RXN9W
          TbcISAhHfc9/nEwmysr0xiIR4fiUMXsdxsxzatKH4QVEnjbP5SE0AjamWf6YeEszMgDhC
          JKnicb9VFjcnwPFPyO2uxNEdwlNjZL8xV1qPUulR/smbgybCvGpA4G8YGKGmKs=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - klw+3hwvH1sDF+delv1VtoagAoi9OrbLWLGYghh6gDAfKiDA5wtz8t1mBXukcZdcNtp55
          4kdyNpLmdvKXS3kquGI/S9FawIIAOWn+1Nf+ynOPJXfta/CGcPztTLYkJd7yYnxXNjHEw
          FqyPr411P7yMsau4/PAVT6W6h6hwbz9AP+ga8KapT/WjbyuaD5Pcw4MPawyewi/ckKDjA
          EN34p/+SeQZlOu4mMg0hhox/m0Xi92Fktp8I1Py/JvCt+48+regDYj/d2I9sPD4P4IJlH
          OZZ83Rkckkr+CJTNpgsAWRWA92P+gul5rcOdzzPH1B7/PZPWGjoJ0rVaKvpibX6jLF0hG
          tT7MPHqvHVtf6L/jTtJJJNBS5V2HrZVhpxMQnPq1s3sKOZRw8z09+Vv64W4Q3I8O4aQe4
          H0vJ1R8fWShvHxd53D8NiDPfabaI5+SWwLWVUmR3xS3hz4a4lIuOAXg9ABzgww7D+BwbQ
          Nq4tDJv9uqxv9HBSxQMOXyltJIquQOd9+vGlCAyoVYvxxhnVwIydFEWzt5qiomTAE0vsO
          qICtHPGMKZ83VBR/7gwF3Jw4y8MGC1Dc4DZbg5l/rWdvaG952Xle51g8xuy7ouswIPPdj
          295UPDeykZOCcgfmxzPtdTiTaDqrNM/zsg17xf4fbpmy8vHqaaoZf5CL3NPj2A=

- semaphore:
    name: semaphore-deb-packaging-push-ovs-3.3
    max: 1

- semaphore:
    name: semaphore-deb-packaging-push-ovs-3.4
    max: 1

- semaphore:
    name: semaphore-deb-packaging-push-ovs-3.5
    max: 1

- semaphore:
    name: semaphore-deb-packaging-push-ovs-3.5-aarch64
    max: 1

- semaphore:
    name: semaphore-deb-packaging-push-open-iscsi-bookworm-backports
    max: 1

- job:
    name: deb-packaging-build-open-iscsi-bookworm-backports
    pre-run: playbooks/pre-open-iscsi.yml
    run: playbooks/build-open-iscsi.yml

- job:
    name: deb-packaging-push-open-iscsi-bookworm-backports
    parent: deb-packaging-build-open-iscsi-bookworm-backports
    semaphores:
      - name: semaphore-deb-packaging-push-open-iscsi-bookworm-backports
    vars:
      open_iscsi_push: true
    secrets:
      - name: secret
        secret: SECRET_DEB_PACKAGING
        pass-to-parent: true

- job:
    name: deb-packaging-build-ovs-3.3
    pre-run: playbooks/pre-ovs.yml
    run: playbooks/build-ovs.yml
    nodeset:
      nodes:
        - name: debian-bookworm
          label: debian-bookworm
        - name: ubuntu-jammy
          label: ubuntu-jammy
    vars:
      ovs_version: "v3.3.5"

- job:
    name: deb-packaging-build-ovs-3.4
    pre-run: playbooks/pre-ovs.yml
    run: playbooks/build-ovs.yml
    nodeset:
      nodes:
        - name: debian-bookworm
          label: debian-bookworm
        - name: ubuntu-noble
          label: ubuntu-noble
    vars:
      ovs_version: "v3.4.3"

- job:
    name: deb-packaging-build-ovs-3.5
    pre-run: playbooks/pre-ovs.yml
    run: playbooks/build-ovs.yml
    nodeset:
      nodes:
        - name: debian-bookworm
          label: debian-bookworm
        - name: ubuntu-noble
          label: ubuntu-noble
    vars:
      ovs_version: "v3.5.2"

- job:
    name: deb-packaging-build-ovs-3.5-aarch64
    pre-run: playbooks/pre-ovs-aarch64.yml
    run: playbooks/build-ovs-aarch64.yml
    nodeset:
      nodes:
        - name: ubuntu-noble
          label: ubuntu-noble
    vars:
      ovs_version: "v3.5.2"

- job:
    name: deb-packaging-push-ovs-3.3
    parent: deb-packaging-build-ovs-3.3
    semaphores:
      - name: semaphore-deb-packaging-push-ovs-3.3
    vars:
      ovs_push: true
    secrets:
      - name: secret
        secret: SECRET_DEB_PACKAGING
        pass-to-parent: true

- job:
    name: deb-packaging-push-ovs-3.4
    parent: deb-packaging-build-ovs-3.4
    semaphores:
      - name: semaphore-deb-packaging-push-ovs-3.4
    vars:
      ovs_push: true
    secrets:
      - name: secret
        secret: SECRET_DEB_PACKAGING
        pass-to-parent: true

- job:
    name: deb-packaging-push-ovs-3.5
    parent: deb-packaging-build-ovs-3.5
    semaphores:
      - name: semaphore-deb-packaging-push-ovs-3.5
    vars:
      ovs_push: true
    secrets:
      - name: secret
        secret: SECRET_DEB_PACKAGING
        pass-to-parent: true

- job:
    name: deb-packaging-push-ovs-3.5-aarch64
    parent: deb-packaging-build-ovs-3.5-aarch64
    semaphores:
      - name: semaphore-deb-packaging-push-ovs-3.5-aarch64
    vars:
      ovs_push: true
    secrets:
      - name: secret
        secret: SECRET_DEB_PACKAGING
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        # - deb-packaging-build-ovs-3.3
        # - deb-packaging-build-ovs-3.4
        # - deb-packaging-build-ovs-3.5
        - deb-packaging-build-ovs-3.5-aarch64
        # - deb-packaging-build-open-iscsi-bookworm-backports
        - yamllint
    post:
      jobs:
        - deb-packaging-push-ovs-3.3
        - deb-packaging-push-ovs-3.4
        - deb-packaging-push-ovs-3.5
        - deb-packaging-push-ovs-3.5-aarch64
        - deb-packaging-push-open-iscsi-bookworm-backports
