---
- name: Build open-iscsi packages
  hosts: all

  vars:
    default_docker_registry: osism.harbor.regio.digital
    default_docker_namespace: packages
    default_docker_tag: bookworm-backports

  tasks:
    - name: Log into registry
      community.docker.docker_login:
        registry_url: "{{ docker_registry | default(default_docker_registry) }}"
        username: "foo"
        password: "bar"
      when: true
      no_log: false
