---
- name: Prepare build of qemu packages
  hosts: all

  roles:
    - ensure-docker

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - python3-requests
