---
name: Build ovs

"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ovs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build ovs package
        run: ./scripts/build-ovs.sh

      - name: Upload ovs package
        uses: actions/upload-artifact@v3
        with:
          name: ovs
          path: "*.deb"
          retention-days: 5
