---
name: Build ovs 3.1

"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-ovs-3.1.yml'
      - 'scripts/build-ovs-3.1.sh'
  pull_request:
    paths:
      - '.github/workflows/build-ovs-3.1.yml'
      - 'scripts/build-ovs-3.1.sh'

jobs:
  build-ovs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build ovs package
        run: ./scripts/build-ovs-3.1.sh

      - name: Upload ovs package
        uses: actions/upload-artifact@v3
        with:
          name: ovs
          path: "*.deb"
          retention-days: 5
